### PR TITLE
feat: add difficultes filter #4

### PR DESCRIPTION
**Pull request by ngthuongdoan**
Hey I've done this, please make a review @Vincenius 
https://github.com/Vincenius/workout-lol/issues/4

### CODE REVIEW

**Comment by Vincenius** [comment]
Thanks a lot for your contribution @ngthuongdoan! It already looks good. I only found a small issue - it looks like it's not updating the generated workout after selecting the difficulty. So it still has the exercises with not matching difficulty

**Comment by ngthuongdoan** [comment]
> 

I think if related to the shuffle() function, when I hit the Add button it's still filter as it should be but not showing on the screen. Is it feature or bug?

**Comment by Vincenius** [comment]
Sounds like a bug to me
Do you have time to look into it? I could check it the earliest on Thursday morning

**Comment by ngthuongdoan** [comment]
`const sortedArray = sortByPropertyWithHighDistribution(
        exercises,
        "mainMuscle"
 );`
 
 I saw this, whenever it shuffle -> it's sorted so it's will be the same every time it changes

**Comment by Vincenius** [comment]
The problem was that the useEffect hook to populate "workout" was design to only run on the first data fetch. I also added another hook to update the workout if the difficulties change:

https://github.com/Vincenius/workout-lol/compare/main...add-difficulty#diff-5c805cedf6a23d0579b92bd00464fd86229b42671e761ad43934dc205c739c12R73-R92

I'll merge it soon - but first I want to re-think if it would make sense to have the difficulty selection on another screen / another place :)

Thanks again for your contribution. I'd add you to the readme as contributer if you're fine with that. You can let me know which link I should add to your icon :)

**Comment by ngthuongdoan** [comment]
Thanks, you can use my GitHub profile for simple

https://github.com/ngthuongdoan

**Comment by Vincenius** [comment]
will merge from my branch :) After thinking it through I've decided to move it to the muscles selection

**Pull request closed without merging**
