### PR TITLE
feat: drag-n-drop v1

### PR DESCRIPTION
**Pull request by Snouzy**
here's drag n drop v1. Functional, there's a little style glitch linked to mantine's "timeline".
I don't know how to fix it yet; Maybe we could do just a list to have a fluid comportment ? 

https://github.com/Vincenius/workout-lol/assets/32961176/a77ea693-702a-4a4f-a6d0-3b9489f95cdd

I will check and purpose solutions later !

### CODE REVIEW

**Comment by Vincenius** [comment]
Looks good so far! Yeah, we can change the timeline to a list to make it work.
I'll have a bit more time again on thursday and friday to spend on this project

**Comment by Snouzy** [comment]
K then i'll do it with pleasure maybe today or in the next days ! 💪🏼

**Comment by Vincenius** [comment]
Nice work - looks good! Now some design touches and we should be good :)

btw if you have ideas on how to improve workout.lol feel free to create issues

**Comment by Snouzy** [comment]
@Vincenius here's the commit with the style ⬆️

https://github.com/Vincenius/workout-lol/assets/32961176/532ebe6f-688c-4407-9523-03c8191518c4

**Review by Vincenius — APPROVED** [review]
Great Work!!

**Pull request merged**
